server:
  port: 8088

spring:
  application:
    name: kafka-demo

  kafka:
    bootstrap-servers:
      - 10.211.55.50:9092
    consumer:
      group-id: kafka-demo
      auto-offset-reset: earliest
      auto-commit-interval: 1000
      enable-auto-commit: true
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: root
#    password: 16351018
#    virtual-host: /
#    publisher-confirm-type: CORRELATED
#    template:
#      retry:
#        max-attempts: 3
#        multiplier: 1.0




